import React from "react";
import { makeStyles, Paper } from "@material-ui/core";
import Accordion from "@material-ui/core/Accordion";
import AccordionSummary from "@material-ui/core/AccordionSummary";
import AccordionDetails from "@material-ui/core/AccordionDetails";
import Typography from "@material-ui/core/Typography";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";

const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    [theme.breakpoints.down("xs")]: {
      width: "236%",
    },
  },
  abouttest: {
    fontSize: "30px",
    padding: "10px",
  },
  heading: {
    fontSize: theme.typography.pxToRem(33),
  },
  subtext: {
    fontSize: "15px",
  },
}));

export default function About() {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <Paper>
        <Typography className={classes.abouttest}>
          Frequently Asked Questions
        </Typography>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel1a-content"
            id="panel1a-header"
          >
            <Typography className={classes.heading}>
              What is a tax inovice?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              A tax invoice is the invoice created by a GST registered business
              owner when he sells taxable goods and services. Tax invoices are
              mandatory for claiming Input Tax Credit.
            </Typography>
          </AccordionDetails>
        </Accordion>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is a bill of supply?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              A bill of supply is an invoice generated by a GST registered
              business owner when he sells GST exempt goods or services, or when
              he is registered under the Composition Scheme.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is a GSTIN and how can I get one?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              GSTIN is a unique 15 digit identification number given to a
              taxpayer who registers themselves under the GST law in a
              particular state in India.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              How are interstate and intrastate transactions treated under the
              GST?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              In case of intrastate transactions, two taxes; Central GST(CGST)
              and State GST(SGST) are collected by both Central and State
              Government. If it is an interstate transaction, a combined tax
              called Integrated GST (IGST) is collected by the Central
              Government.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is the time limit to issue invoices in the GST system?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              For services, the tax invoice must be issued within 30 days from
              the date of the service rendered. For goods, it involves two
              criteria. The invoice must be issued before or at the time of
              removal of goods (if the supply involves the movement of goods
              from once place to another), or the invoice must be issued on or
              before the delivery of goods (if the supply does not involve
              physical movement of goods from one place to another).
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              How many copies of invoices are required under the GST?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              If you are selling goods, you need to produce 3 copies (one for
              your customer, one for the transporter of goods, if the sale
              involves movement of goods, and one for your own records). If you
              are providing a service, you need to produce 2 copies (one for
              your customer, and one for your own records).
            </Typography>
          </AccordionDetails>
        </Accordion>
        {/*  */}
        {/*  */}
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is HSN Code, and SAC?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              The Harmonized System of Nomenclature (HSN) is an internationally
              accepted method of naming, classifying and identifying products.
              HSN code is used to classify goods to compute GST. Each product
              has a unique HSN code, which must be mentioned on the invoice.
              Service Accounting Codes (SAC) is a unique code provided for
              recognition, measurement and taxation of services, which must be
              mentioned on the invoice.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is place of supply under the GST?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              Place of supply under the GST is the location of the buyer or
              receiver of the goods or services.
            </Typography>
          </AccordionDetails>
        </Accordion>
        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is reverse charge?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              In the reverse charge mechanism, the buyer or the receiver of
              goods or services is liable to pay taxes instead of the seller.
            </Typography>
          </AccordionDetails>
        </Accordion>

        <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2a-content"
            id="panel2a-header"
          >
            <Typography className={classes.heading}>
              What is mixed and composite supply?
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography className={classes.subtext}>
              Mixed supply under GST is when a taxable person combines two or
              more individual goods or services and sell it for a single price.
              Each of these items can be supplied separately. Composite supply
              under GST means if a supply is comprising two or more goods or
              services that are naturally bundled and sold together. These items
              cannot be sold separately
            </Typography>
          </AccordionDetails>
        </Accordion>
      </Paper>
    </div>
  );
}
